# Project information
site_name: YulinLuo
site_url: https://luoyulin-muii.github.io
site_author: YulinLuo
site_description: >-
  Yulin's Academic Homepage


# Repository
repo_name: luoyulin-muii
repo_url: https://github.com/luoyulin-muii
# repo_url: https://luoyulin-muii.github.io
edit_uri: ""


# Copyright
copyright: Copyright &copy; 2021 - 2022 YulinLuo


# Configuration
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - tabs
    - instant
  palette:
    primary: indigo
    accent: indigo
  # font:
  #   text: Roboto
  #   code: Roboto Mono
  icon:
    logo: material/school
    repo: fontawesome/brands/github
  favicon: ./images/favicon.png


# Page tree
nav:
  - Homepage: index.md


# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/luoyulin-muii

extra_css: [style.css]


# Extensions
# markdown_extensions:
#   - markdown.extensions.admonition
#   - markdown.extensions.attr_list
#   - markdown.extensions.codehilite:
#       guess_lang: false
#   - markdown.extensions.def_list
#   - markdown.extensions.footnotes
#   - markdown.extensions.meta
#   - markdown.extensions.toc:
#       permalink: true
#   - pymdownx.arithmatex
#   - pymdownx.betterem:
#       smart_enable: all
#   - pymdownx.caret
#   - pymdownx.critic
#   - pymdownx.details
#   - pymdownx.emoji:
#       emoji_index: !!python/name:pymdownx.emoji.twemoji
#       emoji_generator: !!python/name:pymdownx.emoji.to_svg
#   # - pymdownx.highlight:
#   #     linenums_style: pymdownx-inline
#   - pymdownx.inlinehilite
#   - pymdownx.keys
#   - pymdownx.magiclink:
#       repo_url_shorthand: true
#       user: squidfunk
#       repo: mkdocs-material
#   - pymdownx.mark
#   - pymdownx.smartsymbols
#   - pymdownx.snippets:
#       check_paths: true
#   - pymdownx.superfences
#   - pymdownx.tabbed
#   - pymdownx.tasklist:
#       custom_checkbox: true
#   - pymdownx.tilde


# Google Analytics
google_analytics:
  - 'UA-162524994-1'
  - auto